version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
volumes:
  webflux_data:

networks:
  app-network:
    driver: bridge